name: Run Tests

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Run xunit tests
      run: dotnet test ./
